### ISSUE TITLE
Change Logo

### ISSUE THREAD

**Issue by TheFatPanda97** [TheFatPanda97/Isomo#18]
# Overview
The current logo is too small. Implement the new logo in both the favicon as well as the navbar.

![image](https://user-images.githubusercontent.com/36747253/82930811-f7fee300-9f53-11ea-8bd1-36b2a1176ec6.png)
![image](https://user-images.githubusercontent.com/36747253/82930842-03520e80-9f54-11ea-9c16-fdfd28edc021.png)

**Comment by BrianLi009** [comment]
The new logo is in the slack channel
